# Generated by Django 4.2.2 on 2023-08-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(choices=[('Spinning Rods', 'Spinning Rods'), ('Baitcasting Rods', 'Baitcasting Rods'), ('Fly Rods', 'Fly Rods'), ('Surf Rods', 'Surf Rods'), ('Telescopic Rods', 'Telescopic Rods')], max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('color', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Red', 'Red'), ('Gray', 'Gray'), ('Light Blue', 'Light Blue')], max_length=20)),
            ],
        ),
    ]
