# Generated by Django 4.2.8 on 2023-12-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='size',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fish',
            name='color',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('Gray', 'Gray'), ('Light Yellow', 'Light Yellow')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fish',
            name='model',
            field=models.CharField(choices=[("Abu Garcia 6'6 ft Salty Fighter ", "Abu Garcia 6'6 ft Salty Fighter "), ('Neon Blue Wagtail Platy Fish', 'Neon Blue Wagtail Platy Fish'), ('Mickey Mouse Platy Fish', 'Mickey Mouse Platy Fish'), ('Parrot Platy Fish', 'Parrot Platy Fish'), ('Hifin Tuxedo Yellow Platy Fish', 'Hifin Tuxedo Yellow Platy Fish')], max_length=50),
        ),
    ]
