# Generated by Django 4.2.8 on 2023-12-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0002_fish_size_alter_fish_color_alter_fish_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('Gray', 'Gray'), ('Light Yellow', 'Light Yellow')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fish',
            name='model',
            field=models.CharField(choices=[('Spinning Rods', 'Spinning Rods'), ('Baitcasting Rods', 'NBaitcasting Rods'), ('Fly Rods', 'Fly Rods'), ('Surf Rods', 'Surf Rods'), ('Telescopic Rods', 'Telescopic Rods')], max_length=50),
        ),
    ]
